import "./globals.css";
import Providers from "./providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Footer from "@/components/footer";
import ChatButton from "@/components/message";
import { getEmploye } from "@/lib/api";
import FooterWrapper from "@/components/footer/FooterWrapper";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const employe = await getEmploye();

  return (
    <html lang="en">
      <body className="bg-stone-100">
        <Providers>
          <AntdRegistry>{children}</AntdRegistry>
          <FooterWrapper employes={employe} />
        </Providers>
      </body>
    </html>
  );
}
